//go:build !ignore_autogenerated

// Code generated for the eBPF-P4 project.
// Minimal deepcopy implementations for the GradientAggregation CRD types.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// --- GradientAggregation ---

func (in *GradientAggregation) DeepCopyInto(out *GradientAggregation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *GradientAggregation) DeepCopy() *GradientAggregation {
	if in == nil {
		return nil
	}
	out := new(GradientAggregation)
	in.DeepCopyInto(out)
	return out
}

func (in *GradientAggregation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- GradientAggregationList ---

func (in *GradientAggregationList) DeepCopyInto(out *GradientAggregationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GradientAggregation, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *GradientAggregationList) DeepCopy() *GradientAggregationList {
	if in == nil {
		return nil
	}
	out := new(GradientAggregationList)
	in.DeepCopyInto(out)
	return out
}

func (in *GradientAggregationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- GradientAggregationSpec ---

func (in *GradientAggregationSpec) DeepCopyInto(out *GradientAggregationSpec) {
	*out = *in
	if in.SmartNICSelector != nil {
		sel := new(SmartNICSelector)
		*sel = *in.SmartNICSelector
		out.SmartNICSelector = sel
	}
	if in.EBPFPolicy != nil {
		pol := new(EBPFPolicy)
		*pol = *in.EBPFPolicy
		out.EBPFPolicy = pol
	}
	if in.Metrics != nil {
		out.Metrics = make([]string, len(in.Metrics))
		copy(out.Metrics, in.Metrics)
	}
}

// --- GradientAggregationStatus ---

func (in *GradientAggregationStatus) DeepCopyInto(out *GradientAggregationStatus) {
	*out = *in
}