#!/bin/bash
# ============================================================
# clean.sh - full cleanup of the eBPF-P4 project
#
# Removes:
#   - Build artifacts (CMake caches, binaries, BPF objects, go.sum)
#   - Experiment results (benchmarks/results/, benchmarks/analysis/)
#   - Kubernetes results (k8s-results/)
#   - Docker containers, images, and KIND clusters for this project
#   - XDP attachments and bpffs-pinned programs
#   - Lingering aggregator processes holding port 9999
#
# Usage:
#   bash scripts/clean.sh                # full cleanup
#   bash scripts/clean.sh --keep-images  # keep docker images
#   bash scripts/clean.sh --source-only  # only build artifacts
# ============================================================
set +e
cd "$(dirname "$0")/.."
ROOT=$(pwd)

KEEP_IMAGES=0
SOURCE_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --keep-images) KEEP_IMAGES=1 ;;
        --source-only) SOURCE_ONLY=1 ;;
        *) echo "Unknown option: $arg"; exit 1 ;;
    esac
done

# ------------------------------------------------------------
# 1. Build artifacts
# ------------------------------------------------------------
printf 'Removing build artifacts\n'
make -C ebpf clean >/dev/null 2>&1 || true
rm -rf client_lib/build tests/build examples/build benchmarks/build operator/bin
find . -name "CMakeCache.txt" -delete 2>/dev/null
find . -name "CMakeFiles" -type d -exec rm -rf {} + 2>/dev/null
find . -name "*.o"     -delete 2>/dev/null
find . -name "*.so"    -delete 2>/dev/null
find . -name "*.bpf.o" -delete 2>/dev/null
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null
find . -name "*.pyc" -delete 2>/dev/null

# operator/go.sum is regenerated by docker build
rm -f operator/go.sum

if [ $SOURCE_ONLY -eq 1 ]; then
    printf 'Source-only mode: keeping experiment results.\n'
    printf 'Clean complete (source-only).\n'
    exit 0
fi

# ------------------------------------------------------------
# 2. Experiment and ablation results
# ------------------------------------------------------------
printf 'Removing experiment results\n'
rm -f  benchmarks/results/*.csv
rm -f  benchmarks/results/*.txt
rm -f  benchmarks/results/*.log
rm -rf benchmarks/results/ablation
rm -f  benchmarks/analysis/*.png

printf 'Removing Kubernetes experiment results\n'
rm -rf k8s-results

# ------------------------------------------------------------
# 3. Docker containers, images, and KIND clusters
# ------------------------------------------------------------
printf 'Stopping and removing project containers\n'
# Any container whose name contains "ebpf" or "kind"
for filter in "name=ebpf" "name=kind" "name=ebpf-p4"; do
    ids=$(docker ps -aq --filter "$filter" 2>/dev/null)
    if [ -n "$ids" ]; then
        sudo docker stop -t 0 $ids >/dev/null 2>&1 || true
        sudo docker rm -f  $ids >/dev/null 2>&1 || true
    fi
done

printf 'Deleting KIND clusters\n'
kind delete cluster --name ebpf-p4   2>/dev/null || true
kind delete cluster --name ebpf-test 2>/dev/null || true

printf 'Removing KIND docker network\n'
sudo docker network rm kind 2>/dev/null || true

if [ $KEEP_IMAGES -eq 0 ]; then
    printf 'Removing project docker images\n'
    sudo docker rmi -f ebpf-p4-agg:latest      2>/dev/null || true
    sudo docker rmi -f ebpf-p4-operator:latest 2>/dev/null || true
fi

# ------------------------------------------------------------
# 4. XDP attachment and bpffs state
# ------------------------------------------------------------
printf 'Detaching XDP from loopback\n'
sudo ip link set dev lo xdp off 2>/dev/null || true

printf 'Removing bpffs state\n'
sudo rm -rf /sys/fs/bpf/xdp_aggregator \
            /sys/fs/bpf/xdp_aggregator_pass \
            /sys/fs/bpf/xdp_ablation \
            /sys/fs/bpf/xdp_ablation_pass 2>/dev/null || true

# ------------------------------------------------------------
# 5. Aggregator processes and port 9999
# ------------------------------------------------------------
printf 'Releasing UDP port 9999\n'
sudo pkill -KILL -f '[u]serspace_aggregator'  >/dev/null 2>&1 || true
sudo pkill -KILL -f '[e]cho_aggregator'       >/dev/null 2>&1 || true
sudo pkill -KILL -f '[x]dp_aggregator'        >/dev/null 2>&1 || true
command -v fuser >/dev/null 2>&1 && \
    sudo fuser -k -KILL 9999/udp >/dev/null 2>&1 || true
command -v lsof  >/dev/null 2>&1 && \
    sudo lsof -t -iUDP:9999 2>/dev/null | xargs -r sudo kill -9 2>/dev/null || true

sleep 1
if ss -lun 2>/dev/null | grep -q ':9999'; then
    printf 'ERROR: port 9999 still busy\n'
    ss -lunp 2>/dev/null | grep ':9999' || true
    exit 1
fi
printf '  port 9999 is free\n'

# ------------------------------------------------------------
# 6. Recreate results directory and summarize
# ------------------------------------------------------------
mkdir -p benchmarks/results

printf '\nClean complete.\n'
printf 'Removing Kubernetes experiment results\n'
sudo rm -rf k8s-results 2>/dev/null || rm -rf k8s-results 2>/dev/null || true
printf 'Remaining KIND clusters: '
(kind get clusters 2>/dev/null | tr '\n' ' ') || true
printf '\nRemaining docker images matching ebpf:\n'
sudo docker images 2>/dev/null | awk 'NR==1 || /ebpf/' | sed 's/^/  /' || true