link_directories(${CMAKE_BINARY_DIR}/client_lib)

add_executable(latency_benchmark latency_benchmark.cpp)
target_link_libraries(latency_benchmark switchml pthread)

add_executable(cpu_benchmark cpu_benchmark.cpp)
target_link_libraries(cpu_benchmark switchml pthread)

add_executable(scalability_benchmark scalability_benchmark.cpp)
target_link_libraries(scalability_benchmark switchml pthread)